plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  UseCache: true
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - lib/grape-oas.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/grape_oas/api_model_builders/dry_introspector.rb
    - test/**/*

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - lib/grape_oas/api_model_builders/dry_introspector.rb

Minitest/MultipleAssertions:
  Enabled: false
